"""Scan category registry — pure data, no dependencies."""

TIER_SAFE = "SAFE"
TIER_CAUTION = "CAUTION"


SCAN_CATEGORIES = [
    {
        "id": "user_temp",
        "label": "User Temp Files",
        "icon": "temp",
        "paths": [r"%TEMP%", r"%LOCALAPPDATA%\Temp"],
        "pattern": "*",
        "recursive": True,
        "max_age_days": 1,
        "tier": TIER_SAFE,
        "desc": "Temporary files created by apps in your user profile. Windows and apps recreate these as needed.",
    },
    {
        "id": "win_temp",
        "label": "Windows Temp",
        "icon": "windows",
        "paths": [r"%SystemRoot%\Temp"],
        "pattern": "*",
        "recursive": True,
        "max_age_days": 1,
        "tier": TIER_SAFE,
        "desc": "System-wide temporary files. Some require admin to remove — those are skipped automatically.",
    },
    {
        "id": "recycle_bin",
        "label": "Recycle Bin",
        "icon": "trash",
        "paths": [],
        "pattern": "*",
        "recursive": True,
        "max_age_days": None,
        "tier": TIER_SAFE,
        "desc": "Items already in the Recycle Bin. Emptying permanently deletes them.",
        "special": "recycle_bin",
        "force_permanent": True,
    },
    {
        "id": "thumbcache",
        "label": "Thumbnail Cache",
        "icon": "image",
        "paths": [r"%LOCALAPPDATA%\Microsoft\Windows\Explorer"],
        "pattern": "thumbcache_*.db",
        "recursive": False,
        "max_age_days": None,
        "tier": TIER_SAFE,
        "desc": "Cached thumbnails for Explorer. Windows rebuilds these on demand.",
    },
    {
        "id": "iconcache",
        "label": "Icon Cache",
        "icon": "image",
        "paths": [r"%LOCALAPPDATA%\Microsoft\Windows\Explorer"],
        "pattern": "iconcache_*.db",
        "recursive": False,
        "max_age_days": None,
        "tier": TIER_SAFE,
        "desc": "Cached icons for apps and folders. Windows rebuilds these on demand.",
    },
    {
        "id": "chrome_cache",
        "label": "Chrome Cache",
        "icon": "chrome",
        "paths": [
            r"%LOCALAPPDATA%\Google\Chrome\User Data\*\Cache",
            r"%LOCALAPPDATA%\Google\Chrome\User Data\*\Code Cache",
            r"%LOCALAPPDATA%\Google\Chrome\User Data\*\GPUCache",
        ],
        "pattern": "*",
        "recursive": True,
        "max_age_days": None,
        "tier": TIER_SAFE,
        "desc": "Cached web content from Chrome. Does not delete bookmarks, history, or passwords.",
    },
    {
        "id": "edge_cache",
        "label": "Edge Cache",
        "icon": "edge",
        "paths": [
            r"%LOCALAPPDATA%\Microsoft\Edge\User Data\*\Cache",
            r"%LOCALAPPDATA%\Microsoft\Edge\User Data\*\Code Cache",
            r"%LOCALAPPDATA%\Microsoft\Edge\User Data\*\GPUCache",
        ],
        "pattern": "*",
        "recursive": True,
        "max_age_days": None,
        "tier": TIER_SAFE,
        "desc": "Cached web content from Edge. Does not delete bookmarks, history, or passwords.",
    },
    {
        "id": "firefox_cache",
        "label": "Firefox Cache",
        "icon": "firefox",
        "paths": [r"%LOCALAPPDATA%\Mozilla\Firefox\Profiles\*\cache2"],
        "pattern": "*",
        "recursive": True,
        "max_age_days": None,
        "tier": TIER_SAFE,
        "desc": "Cached web content from Firefox. Does not affect bookmarks or logins.",
    },
    {
        "id": "brave_cache",
        "label": "Brave Cache",
        "icon": "browser",
        "paths": [
            r"%LOCALAPPDATA%\BraveSoftware\Brave-Browser\User Data\*\Cache",
            r"%LOCALAPPDATA%\BraveSoftware\Brave-Browser\User Data\*\Code Cache",
        ],
        "pattern": "*",
        "recursive": True,
        "max_age_days": None,
        "tier": TIER_SAFE,
        "desc": "Cached web content from Brave.",
    },
    {
        "id": "crash_dumps",
        "label": "Crash Dumps",
        "icon": "warning",
        "paths": [
            r"%LOCALAPPDATA%\CrashDumps",
            r"%SystemRoot%\Minidump",
            r"%SystemRoot%\LiveKernelReports",
        ],
        "pattern": "*",
        "recursive": True,
        "max_age_days": None,
        "tier": TIER_SAFE,
        "desc": "Memory dumps from app or system crashes. Only useful for debugging.",
    },
    {
        "id": "delivery_opt",
        "label": "Delivery Optimization Cache",
        "icon": "download",
        "paths": [r"%SystemRoot%\SoftwareDistribution\DeliveryOptimization\Cache"],
        "pattern": "*",
        "recursive": True,
        "max_age_days": None,
        "tier": TIER_SAFE,
        "desc": "Windows peer-to-peer update cache. Safe to clear.",
    },
    {
        "id": "win_update",
        "label": "Windows Update Cache",
        "icon": "update",
        "paths": [r"%SystemRoot%\SoftwareDistribution\Download"],
        "pattern": "*",
        "recursive": True,
        "max_age_days": 30,
        "tier": TIER_CAUTION,
        "desc": "Downloaded Windows Update files older than 30 days. Clearing while an update is pending may force a redownload.",
    },
    {
        "id": "prefetch",
        "label": "Prefetch",
        "icon": "bolt",
        "paths": [r"%SystemRoot%\Prefetch"],
        "pattern": "*.pf",
        "recursive": False,
        "max_age_days": None,
        "tier": TIER_CAUTION,
        "desc": "Windows uses these to launch apps faster. Clearing causes a small one-time slowdown on first app launch.",
    },
    {
        "id": "downloads_old",
        "label": "Old Downloads (180+ days)",
        "icon": "download",
        "paths": [r"%USERPROFILE%\Downloads"],
        "pattern": "*",
        "recursive": True,
        "max_age_days": 180,
        "tier": TIER_CAUTION,
        "desc": "Files in your Downloads folder you haven't touched in 6+ months. Review before deleting.",
    },
    {
        "id": "win_logs",
        "label": "Windows Logs",
        "icon": "log",
        "paths": [r"%SystemRoot%\Logs", r"%SystemRoot%\debug"],
        "pattern": "*",
        "recursive": True,
        "max_age_days": 30,
        "tier": TIER_CAUTION,
        "desc": "System log files older than 30 days.",
    },
]


def by_id(category_id):
    return next((c for c in SCAN_CATEGORIES if c["id"] == category_id), None)
